// >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
// ------------------------------------------------------------------
// Copyright (c) 2019-2025 by Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// ------------------------------------------------------------------
//
// IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPELÃƒÂ¢Ã¢â‚¬Å¾Ã‚Â¢
// DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.
//
// Lattice grants permission to use this code pursuant to the
// terms of the Lattice Propel License Agreement.
//
// DISCLAIMER:
//
//  LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
//  EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE
//  PROPEL LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE
//  SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR
//  FITNESS FOR A PARTICULAR PURPOSE.  LATTICE DOES NOT WARRANT THAT THE
//  FUNCTIONS CONTAINED HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT
//  LICENSEE'S OPERATION OF ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE
//  OR ITS CONTENTS WILL BE UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS
//  HEREIN WILL BE CORRECTED.  LICENSEE ASSUMES RESPONSIBILITY FOR 
//  SELECTION OF MATERIALS TO ACHIEVE ITS INTENDED RESULTS, AND FOR THE
//  PROPER INSTALLATION, USE, AND RESULTS OBTAINED THEREFROM.  LICENSEE
//  ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING DEFECTIVE
//  OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT, LICENSEE SHALL
//  ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE, CORRECTION, OR
//  ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
//  SOFTWARE.  IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
//  INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
//  PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS, EVEN IF
//  LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. LATTICE'S
//  SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH ABOVE. 
//  LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS OR
//  USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY
//  RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY
//  THE USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE
//  USE OF FORMAL SOFTWARE VALIDATION METHODS.
// ------------------------------------------------------------------

/* synthesis translate_off*/
`define SBP_SIMULATION
/* synthesis translate_on*/
`ifndef SBP_SIMULATION
`define SBP_SYNTHESIS
`endif
//
// Verific Verilog Description of module Project_Wafer_ACX
//
module Project_Wafer_ACX (instruction, prediction, clk, done, resetn, addr, data);
    input [31:0]instruction;
    output [3:0]prediction;
    input clk;
    output done;
    input resetn;
	input wire [17:0] addr; 
    output reg signed [7:0] data ;
    
    wire [31:0]AXI_Interface_inst_instruction_netbus;
    wire [63:0]soc_axi_full_inst_m_axi_araddr_netbus;
    wire [1:0]soc_axi_full_inst_m_axi_arburst_netbus;
    wire [3:0]soc_axi_full_inst_m_axi_arcache_netbus;
    wire [11:0]soc_axi_full_inst_m_axi_arid_netbus;
    wire [7:0]soc_axi_full_inst_m_axi_arlen_netbus;
    wire [2:0]soc_axi_full_inst_m_axi_arprot_netbus;
    wire [3:0]soc_axi_full_inst_m_axi_arqos_netbus;
    wire [2:0]soc_axi_full_inst_m_axi_arsize_netbus;
    wire [63:0]soc_axi_full_inst_m_axi_awaddr_netbus;
    wire [1:0]soc_axi_full_inst_m_axi_awburst_netbus;
    wire [3:0]soc_axi_full_inst_m_axi_awcache_netbus;
    wire [11:0]soc_axi_full_inst_m_axi_awid_netbus;
    wire [7:0]soc_axi_full_inst_m_axi_awlen_netbus;
    wire [2:0]soc_axi_full_inst_m_axi_awprot_netbus;
    wire [3:0]soc_axi_full_inst_m_axi_awqos_netbus;
    wire [2:0]soc_axi_full_inst_m_axi_awsize_netbus;
    wire [127:0]soc_axi_full_inst_m_axi_wdata_netbus;
    wire [15:0]soc_axi_full_inst_m_axi_wstrb_netbus;
    wire [31:0]pipeline_cpu_inst_result_netbus;
    wire [127:0]AXI_Interface_inst_rdata_netbus;
    wire [11:0]soc_axi_full_inst_s_axi_bid_netbus;
    wire [1:0]soc_axi_full_inst_s_axi_bresp_netbus;
    wire [127:0]soc_axi_full_inst_s_axi_rdata_netbus;
    wire [11:0]soc_axi_full_inst_s_axi_rid_netbus;
    wire [1:0]soc_axi_full_inst_s_axi_rresp_netbus;
    
    wire soc_axi_full_inst_m_axi_arlock_net, soc_axi_full_inst_m_axi_arvalid_net, 
        soc_axi_full_inst_m_axi_awlock_net, soc_axi_full_inst_m_axi_awvalid_net, 
        soc_axi_full_inst_m_axi_bready_net, soc_axi_full_inst_m_axi_rready_net, 
        soc_axi_full_inst_m_axi_wlast_net, soc_axi_full_inst_m_axi_wvalid_net, 
        soc_axi_full_inst_s_axi_arready_net, soc_axi_full_inst_s_axi_awready_net, 
        soc_axi_full_inst_s_axi_bvalid_net, soc_axi_full_inst_s_axi_rlast_net, 
        soc_axi_full_inst_s_axi_rvalid_net, soc_axi_full_inst_s_axi_wready_net;
    wire [31:0]CNN_Accelerator_Engine_inst_argmax_data_in0_netbus;
    wire [31:0]CNN_Accelerator_Engine_inst_argmax_data_in1_netbus;
    wire [31:0]CNN_Accelerator_Engine_inst_argmax_data_in2_netbus;
    wire [31:0]CNN_Accelerator_Engine_inst_argmax_data_in3_netbus;
    wire [31:0]CNN_Accelerator_Engine_inst_argmax_data_in4_netbus;
    wire [31:0]CNN_Accelerator_Engine_inst_argmax_data_in5_netbus;
    wire [31:0]CNN_Accelerator_Engine_inst_argmax_data_in6_netbus;
    wire [31:0]CNN_Accelerator_Engine_inst_argmax_data_in7_netbus;
    wire [31:0]CNN_Accelerator_Engine_inst_argmax_data_in8_netbus;
    wire [4:0]CNN_Accelerator_Engine_inst_argmax_img_netbus;
    wire [3:0]argmax32_9_1_inst_max_index_netbus;
    wire [3:0]CNN_Accelerator_Engine_inst_dense_read_addr_netbus;
    wire [31:0]dense_layer_2x_128_to_9_inst_read_data_netbus;
    wire [4:0]execute_stage_inst_cnn_img_index_netbus;
    wire [3:0]CNN_Accelerator_Engine_inst_predicted_class_netbus;
    
    wire argmax32_9_1_inst_done_net, CNN_Accelerator_Engine_inst_argmax_start_net, 
        dense_layer_2x_128_to_9_inst_done_net, CNN_Accelerator_Engine_inst_dense_start_net, 
        CNN_Accelerator_Engine_inst_done_net, execute_stage_inst_cnn_start_net;
    wire [5:0]std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_bias_addr_netbus;
    wire [7:0]biases_rom_1_inst_data_netbus;
    wire [7:0]dense_layer_1x_1280_256_128_bn_relu6_top_inst_bias_addr_netbus;
    wire [7:0]biases_rom_dense_layer_1x_1280_256_128_bn_relu6_inst_data_netbus;
    wire [3:0]dense_layer_2x_128_to_9_inst_bias_addr_netbus;
    wire [7:0]biases_rom_dense_layer_2x_128_to_9_inst_data_netbus;
    wire [5:0]depthandpointwise_conv2d_112_56_2x_144ch_inst_filter_idx_netbus;
    wire [7:0]biases_rom_depthwise_pointwise_2_inst_data_netbus;
    wire [6:0]depthandpointwise_conv2d_28_7_3x_1280ch_inst_filter_idx_netbus;
    wire [7:0]biases_rom_depthwise_pointwise_3_inst_data_netbus;
    wire [11:0]bootloader_rom_inst_m_axi_bid_netbus;
    wire [1:0]bootloader_rom_inst_m_axi_bresp_netbus;
    wire [11:0]bootloader_rom_inst_m_axi_rid_netbus;
    wire [1:0]bootloader_rom_inst_m_axi_rresp_netbus;
    wire [63:0]bootloader_rom_inst_s_axi_araddr_netbus;
    wire [1:0]bootloader_rom_inst_s_axi_arburst_netbus;
    wire [3:0]bootloader_rom_inst_s_axi_arcache_netbus;
    wire [11:0]bootloader_rom_inst_s_axi_arid_netbus;
    wire [7:0]bootloader_rom_inst_s_axi_arlen_netbus;
    wire [2:0]bootloader_rom_inst_s_axi_arprot_netbus;
    wire [3:0]bootloader_rom_inst_s_axi_arqos_netbus;
    wire [2:0]bootloader_rom_inst_s_axi_arsize_netbus;
    wire [63:0]bootloader_rom_inst_s_axi_awaddr_netbus;
    wire [1:0]bootloader_rom_inst_s_axi_awburst_netbus;
    wire [3:0]bootloader_rom_inst_s_axi_awcache_netbus;
    wire [11:0]bootloader_rom_inst_s_axi_awid_netbus;
    wire [7:0]bootloader_rom_inst_s_axi_awlen_netbus;
    wire [2:0]bootloader_rom_inst_s_axi_awprot_netbus;
    wire [3:0]bootloader_rom_inst_s_axi_awqos_netbus;
    wire [2:0]bootloader_rom_inst_s_axi_awsize_netbus;
    wire [127:0]bootloader_rom_inst_s_axi_wdata_netbus;
    wire [15:0]bootloader_rom_inst_s_axi_wstrb_netbus;
    
    wire soc_axi_full_inst_bootloader_start_net, bootloader_rom_inst_m_axi_arready_net, 
        bootloader_rom_inst_m_axi_awready_net, bootloader_rom_inst_m_axi_bvalid_net, 
        bootloader_rom_inst_m_axi_rlast_net, bootloader_rom_inst_m_axi_rvalid_net, 
        bootloader_rom_inst_m_axi_wready_net, bootloader_rom_inst_s_axi_arlock_net, 
        bootloader_rom_inst_s_axi_arvalid_net, bootloader_rom_inst_s_axi_awlock_net, 
        bootloader_rom_inst_s_axi_awvalid_net, bootloader_rom_inst_s_axi_bready_net, 
        bootloader_rom_inst_s_axi_rready_net, bootloader_rom_inst_s_axi_wlast_net, 
        bootloader_rom_inst_s_axi_wvalid_net;
    wire [31:0]decode_stage_inst_imm_out_netbus;
    wire [31:0]pipeline_cpu_inst_if_id_instr_netbus;
    wire [31:0]decode_stage_inst_instr_out_netbus;
    wire [4:0]decode_stage_inst_rd_out_netbus;
    wire [4:0]decode_stage_inst_rf_rs1_addr_netbus;
    wire [31:0]register_file_inst_rs1_data_netbus;
    wire [31:0]register_file_1_inst_rs1_data_netbus;
    wire [31:0]register_file_2_inst_rs1_data_netbus;
    wire [31:0]register_file_3_inst_rs1_data_netbus;
    wire [31:0]register_file_4_inst_rs1_data_netbus;
    wire [31:0]register_file_5_inst_rs1_data_netbus;
    wire [31:0]register_file_6_inst_rs1_data_netbus;
    wire [31:0]register_file_7_inst_rs1_data_netbus;
    wire [31:0]register_file_8_inst_rs1_data_netbus;
    wire [31:0]register_file_9_inst_rs1_data_netbus;
    wire [4:0]decode_stage_inst_rf_rs2_addr_netbus;
    wire [31:0]register_file_inst_rs2_data_netbus;
    wire [31:0]register_file_1_inst_rs2_data_netbus;
    wire [31:0]register_file_2_inst_rs2_data_netbus;
    wire [31:0]register_file_3_inst_rs2_data_netbus;
    wire [31:0]register_file_4_inst_rs2_data_netbus;
    wire [31:0]register_file_5_inst_rs2_data_netbus;
    wire [31:0]register_file_6_inst_rs2_data_netbus;
    wire [31:0]register_file_7_inst_rs2_data_netbus;
    wire [31:0]register_file_8_inst_rs2_data_netbus;
    wire [31:0]register_file_9_inst_rs2_data_netbus;
    wire [31:0]decode_stage_inst_rs1_data_out_netbus;
    wire [4:0]decode_stage_inst_rs1_out_netbus;
    wire [31:0]decode_stage_inst_rs2_data_out_netbus;
    wire [4:0]decode_stage_inst_rs2_out_netbus;
    
    wire pipeline_cpu_inst_if_id_valid_net, decode_stage_inst_is_accel_out_net, 
        decode_stage_inst_rd_valid_out_net;
    wire [17:0]dense_layer_1x_1280_256_128_bn_relu6_top_inst_weights_addr_netbus;
    wire [7:0]dense_1x_layer_weights_block0_rom_inst_data_netbus;
    wire [31:0]dense_layer_1x_1280_256_128_bn_relu6_top_inst_mp_read_addr_netbus;
    wire [3:0]maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_read_data_netbus;
    wire [6:0]dense_layer_2x_128_to_9_inst_dense_read_addr_netbus;
    wire [3:0]dense_layer_1x_1280_256_128_bn_relu6_top_inst_read_data_netbus;
    wire [7:0]dense_layer_1x_1280_256_128_bn_relu6_top_inst_scale_addr_netbus;
    wire [7:0]scale_rom_dense_layer_1x_1280_256_128_bn_relu6_inst_data_netbus;
    wire [7:0]dense_layer_1x_1280_256_128_bn_relu6_top_inst_shift_addr_netbus;
    wire [7:0]shift_rom_dense_layer_1x_1280_256_128_bn_relu6_inst_data_netbus;
    
    wire dense_layer_1x_1280_256_128_bn_relu6_top_inst_done_net, maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_done_net, 
        dense_layer_1x_1280_256_128_bn_relu6_top_inst_mp_start_net, dense_layer_2x_128_to_9_inst_dense_start_net;
    wire [10:0]dense_layer_2x_128_to_9_inst_weight_addr_netbus;
    wire [7:0]weights_rom_dense_layer_2x_128_to_9_inst_data_netbus;
    wire [9:0]depthandpointwise_conv2d_112_56_2x_144ch_inst_mram_addr_a_netbus;
    wire [31:0]depthandpointwise_conv2d_112_56_2x_144ch_inst_mram_din_a_netbus;
    wire [31:0]second_order_conv_mram_wrapper_inst_mram_dout_b_netbus;
    wire [3:0]depthandpointwise_conv2d_112_56_2x_144ch_inst_mram_we_a_netbus;
    wire [31:0]depthandpointwise_conv2d_112_56_2x_144ch_inst_pool_read_addr_netbus;
    wire [3:0]maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_read_data_netbus;
    wire [31:0]maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_conv2d_read_addr_netbus;
    wire [3:0]depthandpointwise_conv2d_112_56_2x_144ch_inst_read_data_netbus;
    wire [7:0]scale_rom_depthwise_pointwise_2_inst_data_netbus;
    wire [7:0]shift_rom_depthwise_pointwise_2_inst_data_netbus;
    wire [7:0]weights_rom_depthwise_pointwise_2_inst_data_netbus;
    wire [15:0]depthandpointwise_conv2d_112_56_2x_144ch_inst_weight_idx_netbus;
    
    wire depthandpointwise_conv2d_112_56_2x_144ch_inst_done_net, depthandpointwise_conv2d_112_56_2x_144ch_inst_mram_en_a_net, 
        depthandpointwise_conv2d_112_56_2x_144ch_inst_mram_en_b_net, maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_done_net, 
        depthandpointwise_conv2d_112_56_2x_144ch_inst_pool_start_net, maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_conv2d_start_net;
    wire [9:0]depthandpointwise_conv2d_28_7_3x_1280ch_inst_conv_out_addr_a_netbus;
    wire [31:0]depthandpointwise_conv2d_28_7_3x_1280ch_inst_conv_out_din_a_netbus;
    wire [31:0]mram_conv_model_inst_mram_dout_a_netbus;
    wire [31:0]mram_conv_model_inst_mram_dout_b_netbus;
    wire [3:0]depthandpointwise_conv2d_28_7_3x_1280ch_inst_conv_out_we_a_netbus;
    wire [31:0]depthandpointwise_conv2d_28_7_3x_1280ch_inst_pool_read_addr_netbus;
    wire [3:0]maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_read_data_netbus;
    wire [31:0]maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_conv2d_read_addr_netbus;
    wire [3:0]depthandpointwise_conv2d_28_7_3x_1280ch_inst_read_data_netbus;
    wire [7:0]scale_rom_depthwise_pointwise_3_inst_data_netbus;
    wire [7:0]shift_rom_depthwise_pointwise_3_inst_data_netbus;
    wire [7:0]weights_rom_depthwise_pointwise_3_inst_data_netbus;
    wire [15:0]depthandpointwise_conv2d_28_7_3x_1280ch_inst_weight_idx_netbus;
    
    wire depthandpointwise_conv2d_28_7_3x_1280ch_inst_conv_out_en_a_net, depthandpointwise_conv2d_28_7_3x_1280ch_inst_conv_out_en_b_net, 
        depthandpointwise_conv2d_28_7_3x_1280ch_inst_done_net, maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_done_net, 
        depthandpointwise_conv2d_28_7_3x_1280ch_inst_pool_start_net, maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_conv2d_start_net;
    wire [4:0]execute_stage_inst_ex_rd_netbus;
    wire [31:0]execute_stage_inst_ex_rs2_netbus;
    wire [31:0]execute_stage_inst_ex_val_netbus;
    wire [4:0]pipeline_cpu_inst_id_ex_rs1_idx_netbus;
    wire [4:0]pipeline_cpu_inst_id_ex_rs2_idx_netbus;
    wire [31:0]pipeline_cpu_inst_id_ex_imm_netbus;
    wire [31:0]pipeline_cpu_inst_id_ex_instr_netbus;
    wire [4:0]pipeline_cpu_inst_id_ex_rd_netbus;
    wire [31:0]pipeline_cpu_inst_id_ex_rs1_netbus;
    wire [31:0]pipeline_cpu_inst_id_ex_rs2_netbus;
    
    wire execute_stage_inst_ex_is_cnn_net, execute_stage_inst_ex_valid_net, 
        pipeline_cpu_inst_id_ex_is_accel_net, pipeline_cpu_inst_id_ex_rd_valid_net;
    wire [31:0]fetch_unit_inst_fetch_instr_netbus;
    
    wire fetch_unit_inst_fetch_valid_net;
    wire [15:0]std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus;
    wire [7:0]image_rom_input_32x32_10_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_11_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_12_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_13_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_14_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_15_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_16_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_17_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_18_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_19_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_1_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_20_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_2_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_3_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_4_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_5_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_6_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_7_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_8_inst_data_netbus;
    wire [7:0]image_rom_input_32x32_9_inst_data_netbus;
    wire [31:0]maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_conv2d_read_addr_netbus;
    wire [3:0]std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_read_data_netbus;
    wire [9:0]maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_mram_addr_a_netbus;
    wire [31:0]maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_mram_din_a_netbus;
    wire [31:0]mram_dual_port_max_pool_1_inst_mram_dout_netbus;
    wire [3:0]maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_mram_we_a_netbus;
    
    wire std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_done_net, 
        maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_conv2d_start_net, 
        maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_mram_en_a_net, 
        maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_mram_en_b_net;
    wire [9:0]maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_mram_addr_a_netbus;
    wire [31:0]maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_mram_din_a_netbus;
    wire [31:0]mram_dual_port_max_pool_2_inst_mram_dout_netbus;
    wire [3:0]maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_mram_we_a_netbus;
    
    wire maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_mram_en_a_net, 
        maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_mram_en_b_net;
    wire [9:0]maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_mram_addr_a_netbus;
    wire [31:0]maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_mram_din_a_netbus;
    wire [31:0]mram_model_maxpool_inst_mram_dout_b_netbus;
    wire [3:0]maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_mram_we_a_netbus;
    
    wire maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_mram_en_a_net, 
        maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_mram_en_b_net;
    wire [4:0]pipeline_cpu_inst_ex_mem_rd_netbus;
    wire [31:0]pipeline_cpu_inst_ex_mem_rs2_netbus;
    wire [31:0]pipeline_cpu_inst_ex_mem_val_netbus;
    wire [4:0]memory_stage_inst_mem_wb_rd_netbus;
    wire [31:0]memory_stage_inst_mem_wb_val_netbus;
    
    wire pipeline_cpu_inst_ex_mem_is_cnn_net, pipeline_cpu_inst_ex_mem_valid_net, 
        memory_stage_inst_mem_wb_is_cnn_net, memory_stage_inst_mem_wb_valid_net;
    wire [9:0]std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTA_addr_netbus;
    wire [31:0]mram_dual_port_inst_MRAM_PORTA_rdata_netbus;
    wire [31:0]std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTA_wdata_netbus;
    wire [3:0]std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTA_we_netbus;
    wire [9:0]std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTB_addr_netbus;
    wire [31:0]mram_dual_port_inst_MRAM_PORTB_rdata_netbus;
    
    wire std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTA_en_net, 
        std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTB_en_net, 
        mram_dual_port_inst_MRAM_PORTB_rdata_valid_net;
    wire [4:0]pipeline_cpu_inst_mem_wb_rd_netbus;
    wire [31:0]pipeline_cpu_inst_mem_wb_val_netbus;
    
    wire pipeline_cpu_inst_mem_wb_is_cnn_net, pipeline_cpu_inst_mem_wb_valid_net, 
        writeback_stage_inst_wb_valid_net;
    wire [5:0]std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_scale_addr_netbus;
    wire [7:0]scale_rom_1_inst_data_netbus;
    wire [5:0]std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_shift_addr_netbus;
    wire [7:0]shift_rom_1_inst_data_netbus;
    wire [9:0]std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_weight_addr_netbus;
    wire [7:0]weights_rom_1_inst_data_netbus;
    
    
    AXI_Interface_Minimal AXI_Interface_inst (.instruction({AXI_Interface_inst_instruction_netbus}), 
            .m_axi_araddr({soc_axi_full_inst_m_axi_araddr_netbus}), .m_axi_arburst({soc_axi_full_inst_m_axi_arburst_netbus}), 
            .m_axi_arcache({soc_axi_full_inst_m_axi_arcache_netbus}), .m_axi_arid({soc_axi_full_inst_m_axi_arid_netbus}), 
            .m_axi_arlen({soc_axi_full_inst_m_axi_arlen_netbus}), .m_axi_arprot({soc_axi_full_inst_m_axi_arprot_netbus}), 
            .m_axi_arqos({soc_axi_full_inst_m_axi_arqos_netbus}), .m_axi_arsize({soc_axi_full_inst_m_axi_arsize_netbus}), 
            .m_axi_awaddr({soc_axi_full_inst_m_axi_awaddr_netbus}), .m_axi_awburst({soc_axi_full_inst_m_axi_awburst_netbus}), 
            .m_axi_awcache({soc_axi_full_inst_m_axi_awcache_netbus}), .m_axi_awid({soc_axi_full_inst_m_axi_awid_netbus}), 
            .m_axi_awlen({soc_axi_full_inst_m_axi_awlen_netbus}), .m_axi_awprot({soc_axi_full_inst_m_axi_awprot_netbus}), 
            .m_axi_awqos({soc_axi_full_inst_m_axi_awqos_netbus}), .m_axi_awsize({soc_axi_full_inst_m_axi_awsize_netbus}), 
            .m_axi_wdata({soc_axi_full_inst_m_axi_wdata_netbus}), .m_axi_wstrb({soc_axi_full_inst_m_axi_wstrb_netbus}), 
            .prediction({pipeline_cpu_inst_result_netbus}), .rdata({AXI_Interface_inst_rdata_netbus}), 
            .s_axi_bid({soc_axi_full_inst_s_axi_bid_netbus}), .s_axi_bresp({soc_axi_full_inst_s_axi_bresp_netbus}), 
            .s_axi_rdata({soc_axi_full_inst_s_axi_rdata_netbus}), .s_axi_rid({soc_axi_full_inst_s_axi_rid_netbus}), 
            .s_axi_rresp({soc_axi_full_inst_s_axi_rresp_netbus}), .clk(clk), 
            .m_axi_arlock(soc_axi_full_inst_m_axi_arlock_net), .m_axi_arvalid(soc_axi_full_inst_m_axi_arvalid_net), 
            .m_axi_awlock(soc_axi_full_inst_m_axi_awlock_net), .m_axi_awvalid(soc_axi_full_inst_m_axi_awvalid_net), 
            .m_axi_bready(soc_axi_full_inst_m_axi_bready_net), .m_axi_rready(soc_axi_full_inst_m_axi_rready_net), 
            .m_axi_wlast(soc_axi_full_inst_m_axi_wlast_net), .m_axi_wvalid(soc_axi_full_inst_m_axi_wvalid_net), 
            .reset(resetn), .s_axi_arready(soc_axi_full_inst_s_axi_arready_net), 
            .s_axi_awready(soc_axi_full_inst_s_axi_awready_net), .s_axi_bvalid(soc_axi_full_inst_s_axi_bvalid_net), 
            .s_axi_rlast(soc_axi_full_inst_s_axi_rlast_net), .s_axi_rvalid(soc_axi_full_inst_s_axi_rvalid_net), 
            .s_axi_wready(soc_axi_full_inst_s_axi_wready_net));
    CNN_Accelerator_Engine CNN_Accelerator_Engine_inst (.argmax_data_in0({CNN_Accelerator_Engine_inst_argmax_data_in0_netbus}), 
            .argmax_data_in1({CNN_Accelerator_Engine_inst_argmax_data_in1_netbus}), 
            .argmax_data_in2({CNN_Accelerator_Engine_inst_argmax_data_in2_netbus}), 
            .argmax_data_in3({CNN_Accelerator_Engine_inst_argmax_data_in3_netbus}), 
            .argmax_data_in4({CNN_Accelerator_Engine_inst_argmax_data_in4_netbus}), 
            .argmax_data_in5({CNN_Accelerator_Engine_inst_argmax_data_in5_netbus}), 
            .argmax_data_in6({CNN_Accelerator_Engine_inst_argmax_data_in6_netbus}), 
            .argmax_data_in7({CNN_Accelerator_Engine_inst_argmax_data_in7_netbus}), 
            .argmax_data_in8({CNN_Accelerator_Engine_inst_argmax_data_in8_netbus}), 
            .argmax_img({CNN_Accelerator_Engine_inst_argmax_img_netbus}), 
            .argmax_max_index({argmax32_9_1_inst_max_index_netbus}), .dense_read_addr({CNN_Accelerator_Engine_inst_dense_read_addr_netbus}), 
            .dense_read_data({dense_layer_2x_128_to_9_inst_read_data_netbus}), 
            .input_image_index({execute_stage_inst_cnn_img_index_netbus}), 
            .predicted_class({CNN_Accelerator_Engine_inst_predicted_class_netbus}), 
            .argmax_done(argmax32_9_1_inst_done_net), .argmax_start(CNN_Accelerator_Engine_inst_argmax_start_net), 
            .clk(clk), .dense_done(dense_layer_2x_128_to_9_inst_done_net), 
            .dense_start(CNN_Accelerator_Engine_inst_dense_start_net), .done(CNN_Accelerator_Engine_inst_done_net), 
            .resetn(resetn), .start(execute_stage_inst_cnn_start_net));
    argmax32_9_1 argmax32_9_1_inst (.data_in0({CNN_Accelerator_Engine_inst_argmax_data_in0_netbus}), 
            .data_in1({CNN_Accelerator_Engine_inst_argmax_data_in1_netbus}), 
            .data_in2({CNN_Accelerator_Engine_inst_argmax_data_in2_netbus}), 
            .data_in3({CNN_Accelerator_Engine_inst_argmax_data_in3_netbus}), 
            .data_in4({CNN_Accelerator_Engine_inst_argmax_data_in4_netbus}), 
            .data_in5({CNN_Accelerator_Engine_inst_argmax_data_in5_netbus}), 
            .data_in6({CNN_Accelerator_Engine_inst_argmax_data_in6_netbus}), 
            .data_in7({CNN_Accelerator_Engine_inst_argmax_data_in7_netbus}), 
            .data_in8({CNN_Accelerator_Engine_inst_argmax_data_in8_netbus}), 
            .img({CNN_Accelerator_Engine_inst_argmax_img_netbus}), .max_index({argmax32_9_1_inst_max_index_netbus}), 
            .clk(clk), .done(argmax32_9_1_inst_done_net), .resetn(resetn), 
            .start(CNN_Accelerator_Engine_inst_argmax_start_net));
    biases_rom_1 biases_rom_1_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_bias_addr_netbus}), 
            .data({biases_rom_1_inst_data_netbus}));
    biases_rom_dense_layer_1x_1280_256_128_bn_relu6 biases_rom_dense_layer_1x_1280_256_128_bn_relu6_inst (.addr({dense_layer_1x_1280_256_128_bn_relu6_top_inst_bias_addr_netbus}), 
            .data({biases_rom_dense_layer_1x_1280_256_128_bn_relu6_inst_data_netbus}));
    biases_rom_dense_layer_2x_128_to_9 biases_rom_dense_layer_2x_128_to_9_inst (.addr({dense_layer_2x_128_to_9_inst_bias_addr_netbus}), 
            .data({biases_rom_dense_layer_2x_128_to_9_inst_data_netbus}));
    biases_rom_depthwise_pointwise_2 biases_rom_depthwise_pointwise_2_inst (.addr({depthandpointwise_conv2d_112_56_2x_144ch_inst_filter_idx_netbus}), 
            .data({biases_rom_depthwise_pointwise_2_inst_data_netbus}));
    biases_rom_depthwise_pointwise_3 biases_rom_depthwise_pointwise_3_inst (.addr({depthandpointwise_conv2d_28_7_3x_1280ch_inst_filter_idx_netbus}), 
            .data({biases_rom_depthwise_pointwise_3_inst_data_netbus}));
    Bootloader_ROM bootloader_rom_inst (.m_axi_bid({bootloader_rom_inst_m_axi_bid_netbus}), 
            .m_axi_bresp({bootloader_rom_inst_m_axi_bresp_netbus}), .m_axi_rid({bootloader_rom_inst_m_axi_rid_netbus}), 
            .m_axi_rresp({bootloader_rom_inst_m_axi_rresp_netbus}), .s_axi_araddr({bootloader_rom_inst_s_axi_araddr_netbus}), 
            .s_axi_arburst({bootloader_rom_inst_s_axi_arburst_netbus}), .s_axi_arcache({bootloader_rom_inst_s_axi_arcache_netbus}), 
            .s_axi_arid({bootloader_rom_inst_s_axi_arid_netbus}), .s_axi_arlen({bootloader_rom_inst_s_axi_arlen_netbus}), 
            .s_axi_arprot({bootloader_rom_inst_s_axi_arprot_netbus}), .s_axi_arqos({bootloader_rom_inst_s_axi_arqos_netbus}), 
            .s_axi_arsize({bootloader_rom_inst_s_axi_arsize_netbus}), .s_axi_awaddr({bootloader_rom_inst_s_axi_awaddr_netbus}), 
            .s_axi_awburst({bootloader_rom_inst_s_axi_awburst_netbus}), .s_axi_awcache({bootloader_rom_inst_s_axi_awcache_netbus}), 
            .s_axi_awid({bootloader_rom_inst_s_axi_awid_netbus}), .s_axi_awlen({bootloader_rom_inst_s_axi_awlen_netbus}), 
            .s_axi_awprot({bootloader_rom_inst_s_axi_awprot_netbus}), .s_axi_awqos({bootloader_rom_inst_s_axi_awqos_netbus}), 
            .s_axi_awsize({bootloader_rom_inst_s_axi_awsize_netbus}), .s_axi_wdata({bootloader_rom_inst_s_axi_wdata_netbus}), 
            .s_axi_wstrb({bootloader_rom_inst_s_axi_wstrb_netbus}), .bootloader_start(soc_axi_full_inst_bootloader_start_net), 
            .clk(clk), .m_axi_arready(bootloader_rom_inst_m_axi_arready_net), 
            .m_axi_awready(bootloader_rom_inst_m_axi_awready_net), .m_axi_bvalid(bootloader_rom_inst_m_axi_bvalid_net), 
            .m_axi_rlast(bootloader_rom_inst_m_axi_rlast_net), .m_axi_rvalid(bootloader_rom_inst_m_axi_rvalid_net), 
            .m_axi_wready(bootloader_rom_inst_m_axi_wready_net), .reset(resetn), 
            .s_axi_arlock(bootloader_rom_inst_s_axi_arlock_net), .s_axi_arvalid(bootloader_rom_inst_s_axi_arvalid_net), 
            .s_axi_awlock(bootloader_rom_inst_s_axi_awlock_net), .s_axi_awvalid(bootloader_rom_inst_s_axi_awvalid_net), 
            .s_axi_bready(bootloader_rom_inst_s_axi_bready_net), .s_axi_rready(bootloader_rom_inst_s_axi_rready_net), 
            .s_axi_wlast(bootloader_rom_inst_s_axi_wlast_net), .s_axi_wvalid(bootloader_rom_inst_s_axi_wvalid_net));
    decode_stage decode_stage_inst (.imm_out({decode_stage_inst_imm_out_netbus}), 
            .instr_in({pipeline_cpu_inst_if_id_instr_netbus}), .instr_out({decode_stage_inst_instr_out_netbus}), 
            .rd_out({decode_stage_inst_rd_out_netbus}), .rf_rs1_addr({decode_stage_inst_rf_rs1_addr_netbus}), 
            .rf_rs1_data({register_file_inst_rs1_data_netbus}), .rf_rs1_data_1({register_file_1_inst_rs1_data_netbus}), 
            .rf_rs1_data_2({register_file_2_inst_rs1_data_netbus}), .rf_rs1_data_3({register_file_3_inst_rs1_data_netbus}), 
            .rf_rs1_data_4({register_file_4_inst_rs1_data_netbus}), .rf_rs1_data_5({register_file_5_inst_rs1_data_netbus}), 
            .rf_rs1_data_6({register_file_6_inst_rs1_data_netbus}), .rf_rs1_data_7({register_file_7_inst_rs1_data_netbus}), 
            .rf_rs1_data_8({register_file_8_inst_rs1_data_netbus}), .rf_rs1_data_9({register_file_9_inst_rs1_data_netbus}), 
            .rf_rs2_addr({decode_stage_inst_rf_rs2_addr_netbus}), .rf_rs2_data({register_file_inst_rs2_data_netbus}), 
            .rf_rs2_data_1({register_file_1_inst_rs2_data_netbus}), .rf_rs2_data_2({register_file_2_inst_rs2_data_netbus}), 
            .rf_rs2_data_3({register_file_3_inst_rs2_data_netbus}), .rf_rs2_data_4({register_file_4_inst_rs2_data_netbus}), 
            .rf_rs2_data_5({register_file_5_inst_rs2_data_netbus}), .rf_rs2_data_6({register_file_6_inst_rs2_data_netbus}), 
            .rf_rs2_data_7({register_file_7_inst_rs2_data_netbus}), .rf_rs2_data_8({register_file_8_inst_rs2_data_netbus}), 
            .rf_rs2_data_9({register_file_9_inst_rs2_data_netbus}), .rs1_data_out({decode_stage_inst_rs1_data_out_netbus}), 
            .rs1_out({decode_stage_inst_rs1_out_netbus}), .rs2_data_out({decode_stage_inst_rs2_data_out_netbus}), 
            .rs2_out({decode_stage_inst_rs2_out_netbus}), .clk(clk), .instr_valid(pipeline_cpu_inst_if_id_valid_net), 
            .is_accel_out(decode_stage_inst_is_accel_out_net), .rd_valid_out(decode_stage_inst_rd_valid_out_net), 
            .reset(resetn));
    dense_1x_layer_weights_block0_rom dense_1x_layer_weights_block0_rom_inst (.addr({dense_layer_1x_1280_256_128_bn_relu6_top_inst_weights_addr_netbus}), 
            .data({dense_1x_layer_weights_block0_rom_inst_data_netbus}));
    dense_layer_1x_1280_256_128_bn_relu6_top dense_layer_1x_1280_256_128_bn_relu6_top_inst (.bias_addr({dense_layer_1x_1280_256_128_bn_relu6_top_inst_bias_addr_netbus}), 
            .bias_data({biases_rom_dense_layer_1x_1280_256_128_bn_relu6_inst_data_netbus}), 
            .mp_read_addr({dense_layer_1x_1280_256_128_bn_relu6_top_inst_mp_read_addr_netbus}), 
            .mp_read_data({maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_read_data_netbus}), 
            .read_addr({dense_layer_2x_128_to_9_inst_dense_read_addr_netbus}), 
            .read_data({dense_layer_1x_1280_256_128_bn_relu6_top_inst_read_data_netbus}), 
            .scale_addr({dense_layer_1x_1280_256_128_bn_relu6_top_inst_scale_addr_netbus}), 
            .scale_data({scale_rom_dense_layer_1x_1280_256_128_bn_relu6_inst_data_netbus}), 
            .shift_addr({dense_layer_1x_1280_256_128_bn_relu6_top_inst_shift_addr_netbus}), 
            .shift_data({shift_rom_dense_layer_1x_1280_256_128_bn_relu6_inst_data_netbus}), 
            .weights_addr({dense_layer_1x_1280_256_128_bn_relu6_top_inst_weights_addr_netbus}), 
            .weights_data({dense_1x_layer_weights_block0_rom_inst_data_netbus}), 
            .clk(clk), .done(dense_layer_1x_1280_256_128_bn_relu6_top_inst_done_net), 
            .mp_done(maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_done_net), 
            .mp_start(dense_layer_1x_1280_256_128_bn_relu6_top_inst_mp_start_net), 
            .resetn(resetn), .start(dense_layer_2x_128_to_9_inst_dense_start_net));
    dense_layer_2x_128_to_9 dense_layer_2x_128_to_9_inst (.bias_addr({dense_layer_2x_128_to_9_inst_bias_addr_netbus}), 
            .bias_data({biases_rom_dense_layer_2x_128_to_9_inst_data_netbus}), 
            .dense_read_addr({dense_layer_2x_128_to_9_inst_dense_read_addr_netbus}), 
            .dense_read_data({dense_layer_1x_1280_256_128_bn_relu6_top_inst_read_data_netbus}), 
            .read_addr({CNN_Accelerator_Engine_inst_dense_read_addr_netbus}), 
            .read_data({dense_layer_2x_128_to_9_inst_read_data_netbus}), .weight_addr({dense_layer_2x_128_to_9_inst_weight_addr_netbus}), 
            .weight_data({weights_rom_dense_layer_2x_128_to_9_inst_data_netbus}), 
            .clk(clk), .dense_done(dense_layer_1x_1280_256_128_bn_relu6_top_inst_done_net), 
            .dense_start(dense_layer_2x_128_to_9_inst_dense_start_net), .done(dense_layer_2x_128_to_9_inst_done_net), 
            .resetn(resetn), .start(CNN_Accelerator_Engine_inst_dense_start_net));
    depthandpointwise_conv2d_112_56_2x_144ch depthandpointwise_conv2d_112_56_2x_144ch_inst (.bias_data({biases_rom_depthwise_pointwise_2_inst_data_netbus}), 
            .filter_idx({depthandpointwise_conv2d_112_56_2x_144ch_inst_filter_idx_netbus}), 
            .mram_addr_a({depthandpointwise_conv2d_112_56_2x_144ch_inst_mram_addr_a_netbus}), 
            .mram_din_a({depthandpointwise_conv2d_112_56_2x_144ch_inst_mram_din_a_netbus}), 
            .mram_dout({second_order_conv_mram_wrapper_inst_mram_dout_b_netbus}), 
            .mram_we_a({depthandpointwise_conv2d_112_56_2x_144ch_inst_mram_we_a_netbus}), 
            .pool_read_addr({depthandpointwise_conv2d_112_56_2x_144ch_inst_pool_read_addr_netbus}), 
            .pool_read_data({maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_read_data_netbus}), 
            .read_addr({maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_conv2d_read_addr_netbus}), 
            .read_data({depthandpointwise_conv2d_112_56_2x_144ch_inst_read_data_netbus}), 
            .scale_data({scale_rom_depthwise_pointwise_2_inst_data_netbus}), 
            .shift_data({shift_rom_depthwise_pointwise_2_inst_data_netbus}), 
            .weight_data({weights_rom_depthwise_pointwise_2_inst_data_netbus}), 
            .weight_idx({depthandpointwise_conv2d_112_56_2x_144ch_inst_weight_idx_netbus}), 
            .clk(clk), .done(depthandpointwise_conv2d_112_56_2x_144ch_inst_done_net), 
            .mram_en_a(depthandpointwise_conv2d_112_56_2x_144ch_inst_mram_en_a_net), 
            .mram_en_b(depthandpointwise_conv2d_112_56_2x_144ch_inst_mram_en_b_net), 
            .pool_done(maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_done_net), 
            .pool_start(depthandpointwise_conv2d_112_56_2x_144ch_inst_pool_start_net), 
            .resetn(resetn), .start(maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_conv2d_start_net));
    depthandpointwise_conv2d_28_7_3x_1280ch depthandpointwise_conv2d_28_7_3x_1280ch_inst (.bias_data({biases_rom_depthwise_pointwise_3_inst_data_netbus}), 
            .conv_out_addr_a({depthandpointwise_conv2d_28_7_3x_1280ch_inst_conv_out_addr_a_netbus}), 
            .conv_out_din_a({depthandpointwise_conv2d_28_7_3x_1280ch_inst_conv_out_din_a_netbus}), 
            .conv_out_dout({mram_conv_model_inst_mram_dout_a_netbus}), .conv_out_dout_b({mram_conv_model_inst_mram_dout_b_netbus}), 
            .conv_out_we_a({depthandpointwise_conv2d_28_7_3x_1280ch_inst_conv_out_we_a_netbus}), 
            .filter_idx({depthandpointwise_conv2d_28_7_3x_1280ch_inst_filter_idx_netbus}), 
            .pool_read_addr({depthandpointwise_conv2d_28_7_3x_1280ch_inst_pool_read_addr_netbus}), 
            .pool_read_data({maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_read_data_netbus}), 
            .read_addr({maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_conv2d_read_addr_netbus}), 
            .read_data({depthandpointwise_conv2d_28_7_3x_1280ch_inst_read_data_netbus}), 
            .scale_data({scale_rom_depthwise_pointwise_3_inst_data_netbus}), 
            .shift_data({shift_rom_depthwise_pointwise_3_inst_data_netbus}), 
            .weight_data({weights_rom_depthwise_pointwise_3_inst_data_netbus}), 
            .weight_idx({depthandpointwise_conv2d_28_7_3x_1280ch_inst_weight_idx_netbus}), 
            .clk(clk), .conv_out_en_a(depthandpointwise_conv2d_28_7_3x_1280ch_inst_conv_out_en_a_net), 
            .conv_out_en_b(depthandpointwise_conv2d_28_7_3x_1280ch_inst_conv_out_en_b_net), 
            .done(depthandpointwise_conv2d_28_7_3x_1280ch_inst_done_net), 
            .pool_done(maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_done_net), 
            .pool_start(depthandpointwise_conv2d_28_7_3x_1280ch_inst_pool_start_net), 
            .resetn(resetn), .start(maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_conv2d_start_net));
    execute_stage execute_stage_inst (.cnn_img_index({execute_stage_inst_cnn_img_index_netbus}), 
            .cnn_pred({CNN_Accelerator_Engine_inst_predicted_class_netbus}), 
            .ex_rd({execute_stage_inst_ex_rd_netbus}), .ex_rs2({execute_stage_inst_ex_rs2_netbus}), 
            .ex_val({execute_stage_inst_ex_val_netbus}), .id_ex_rs1_idx({pipeline_cpu_inst_id_ex_rs1_idx_netbus}), 
            .id_ex_rs2_idx({pipeline_cpu_inst_id_ex_rs2_idx_netbus}), .imm_in({pipeline_cpu_inst_id_ex_imm_netbus}), 
            .instr_in({pipeline_cpu_inst_id_ex_instr_netbus}), .rd_in({pipeline_cpu_inst_id_ex_rd_netbus}), 
            .rs1_in({pipeline_cpu_inst_id_ex_rs1_netbus}), .rs2_in({pipeline_cpu_inst_id_ex_rs2_netbus}), 
            .clk(clk), .cnn_done(CNN_Accelerator_Engine_inst_done_net), 
            .cnn_start(execute_stage_inst_cnn_start_net), .ex_is_cnn(execute_stage_inst_ex_is_cnn_net), 
            .ex_valid(execute_stage_inst_ex_valid_net), .id_ex_is_accel(pipeline_cpu_inst_id_ex_is_accel_net), 
            .rd_valid_in(pipeline_cpu_inst_id_ex_rd_valid_net), .reset(resetn));
    fetch_stage fetch_unit_inst (.fetch_instr({fetch_unit_inst_fetch_instr_netbus}), 
            .instr_from_mem({AXI_Interface_inst_instruction_netbus}), .clk(clk), 
            .fetch_valid(fetch_unit_inst_fetch_valid_net), .reset(resetn));
    image_rom_input_32x32_10 image_rom_input_32x32_10_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_10_inst_data_netbus}));
    image_rom_input_32x32_11 image_rom_input_32x32_11_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_11_inst_data_netbus}));
    image_rom_input_32x32_12 image_rom_input_32x32_12_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_12_inst_data_netbus}));
    image_rom_input_32x32_13 image_rom_input_32x32_13_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_13_inst_data_netbus}));
    image_rom_input_32x32_14 image_rom_input_32x32_14_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_14_inst_data_netbus}));
    image_rom_input_32x32_15 image_rom_input_32x32_15_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_15_inst_data_netbus}));
    image_rom_input_32x32_16 image_rom_input_32x32_16_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_16_inst_data_netbus}));
    image_rom_input_32x32_17 image_rom_input_32x32_17_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_17_inst_data_netbus}));
    image_rom_input_32x32_18 image_rom_input_32x32_18_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_18_inst_data_netbus}));
    image_rom_input_32x32_19 image_rom_input_32x32_19_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_19_inst_data_netbus}));
    image_rom_input_32x32_1 image_rom_input_32x32_1_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_1_inst_data_netbus}));
    image_rom_input_32x32_20 image_rom_input_32x32_20_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_20_inst_data_netbus}));
    image_rom_input_32x32_2 image_rom_input_32x32_2_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_2_inst_data_netbus}));
    image_rom_input_32x32_3 image_rom_input_32x32_3_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_3_inst_data_netbus}));
    image_rom_input_32x32_4 image_rom_input_32x32_4_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_4_inst_data_netbus}));
    image_rom_input_32x32_5 image_rom_input_32x32_5_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_5_inst_data_netbus}));
    image_rom_input_32x32_6 image_rom_input_32x32_6_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_6_inst_data_netbus}));
    image_rom_input_32x32_7 image_rom_input_32x32_7_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_7_inst_data_netbus}));
    image_rom_input_32x32_8 image_rom_input_32x32_8_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_8_inst_data_netbus}));
    image_rom_input_32x32_9 image_rom_input_32x32_9_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .data({image_rom_input_32x32_9_inst_data_netbus}));
    maxpool2d_2x2_stride2_16_batches_112_112_32ch maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst (.conv2d_read_addr({maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_conv2d_read_addr_netbus}), 
            .conv2d_read_data({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_read_data_netbus}), 
            .mram_addr_a({maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_mram_addr_a_netbus}), 
            .mram_din_a({maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_mram_din_a_netbus}), 
            .mram_dout({mram_dual_port_max_pool_1_inst_mram_dout_netbus}), 
            .mram_we_a({maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_mram_we_a_netbus}), 
            .read_addr({depthandpointwise_conv2d_112_56_2x_144ch_inst_pool_read_addr_netbus}), 
            .read_data({maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_read_data_netbus}), 
            .clk(clk), .conv2d_done(std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_done_net), 
            .conv2d_start(maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_conv2d_start_net), 
            .done(maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_done_net), 
            .mram_en_a(maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_mram_en_a_net), 
            .mram_en_b(maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_mram_en_b_net), 
            .resetn(resetn), .start(depthandpointwise_conv2d_112_56_2x_144ch_inst_pool_start_net));
    maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst (.conv2d_read_addr({maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_conv2d_read_addr_netbus}), 
            .conv2d_read_data({depthandpointwise_conv2d_112_56_2x_144ch_inst_read_data_netbus}), 
            .mram_addr_a({maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_mram_addr_a_netbus}), 
            .mram_din_a({maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_mram_din_a_netbus}), 
            .mram_dout({mram_dual_port_max_pool_2_inst_mram_dout_netbus}), 
            .mram_we_a({maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_mram_we_a_netbus}), 
            .read_addr({depthandpointwise_conv2d_28_7_3x_1280ch_inst_pool_read_addr_netbus}), 
            .read_data({maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_read_data_netbus}), 
            .clk(clk), .conv2d_done(depthandpointwise_conv2d_112_56_2x_144ch_inst_done_net), 
            .conv2d_start(maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_conv2d_start_net), 
            .done(maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_done_net), 
            .mram_en_a(maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_mram_en_a_net), 
            .mram_en_b(maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_mram_en_b_net), 
            .resetn(resetn), .start(depthandpointwise_conv2d_28_7_3x_1280ch_inst_pool_start_net));
    maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst (.conv2d_read_addr({maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_conv2d_read_addr_netbus}), 
            .conv2d_read_data({depthandpointwise_conv2d_28_7_3x_1280ch_inst_read_data_netbus}), 
            .mram_addr_a({maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_mram_addr_a_netbus}), 
            .mram_din_a({maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_mram_din_a_netbus}), 
            .mram_dout({mram_model_maxpool_inst_mram_dout_b_netbus}), .mram_we_a({maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_mram_we_a_netbus}), 
            .read_addr({dense_layer_1x_1280_256_128_bn_relu6_top_inst_mp_read_addr_netbus}), 
            .read_data({maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_read_data_netbus}), 
            .clk(clk), .conv2d_done(depthandpointwise_conv2d_28_7_3x_1280ch_inst_done_net), 
            .conv2d_start(maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_conv2d_start_net), 
            .done(maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_done_net), 
            .mram_en_a(maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_mram_en_a_net), 
            .mram_en_b(maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_mram_en_b_net), 
            .resetn(resetn), .start(dense_layer_1x_1280_256_128_bn_relu6_top_inst_mp_start_net));
    memory_stage memory_stage_inst (.ex_rd({pipeline_cpu_inst_ex_mem_rd_netbus}), 
            .ex_rs2({pipeline_cpu_inst_ex_mem_rs2_netbus}), .ex_val({pipeline_cpu_inst_ex_mem_val_netbus}), 
            .mem_wb_rd({memory_stage_inst_mem_wb_rd_netbus}), .mem_wb_val({memory_stage_inst_mem_wb_val_netbus}), 
            .clk(clk), .ex_is_cnn(pipeline_cpu_inst_ex_mem_is_cnn_net), 
            .ex_valid(pipeline_cpu_inst_ex_mem_valid_net), .mem_wb_is_cnn(memory_stage_inst_mem_wb_is_cnn_net), 
            .mem_wb_valid(memory_stage_inst_mem_wb_valid_net), .reset(resetn));
    mram_conv_model mram_conv_model_inst (.mram_addr_a({depthandpointwise_conv2d_28_7_3x_1280ch_inst_conv_out_addr_a_netbus}), 
            .mram_din_a({depthandpointwise_conv2d_28_7_3x_1280ch_inst_conv_out_din_a_netbus}), 
            .mram_dout_a({mram_conv_model_inst_mram_dout_a_netbus}), .mram_dout_b({mram_conv_model_inst_mram_dout_b_netbus}), 
            .mram_we_a({depthandpointwise_conv2d_28_7_3x_1280ch_inst_conv_out_we_a_netbus}), 
            .read_addr_b({maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_conv2d_read_addr_netbus}), 
            .clk(clk), .mram_en_a(depthandpointwise_conv2d_28_7_3x_1280ch_inst_conv_out_en_a_net), 
            .mram_en_b(depthandpointwise_conv2d_28_7_3x_1280ch_inst_conv_out_en_b_net), 
            .resetn(resetn));
    mram_dual_port mram_dual_port_inst (.MRAM_PORTA_addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTA_addr_netbus}), 
            .MRAM_PORTA_rdata({mram_dual_port_inst_MRAM_PORTA_rdata_netbus}), 
            .MRAM_PORTA_wdata({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTA_wdata_netbus}), 
            .MRAM_PORTA_we({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTA_we_netbus}), 
            .MRAM_PORTB_addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTB_addr_netbus}), 
            .MRAM_PORTB_rdata({mram_dual_port_inst_MRAM_PORTB_rdata_netbus}), 
            .MRAM_PORTA_en(std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTA_en_net), 
            .MRAM_PORTB_en(std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTB_en_net), 
            .MRAM_PORTB_rdata_valid(mram_dual_port_inst_MRAM_PORTB_rdata_valid_net), 
            .clk(clk), .resetn(resetn));
    mram_model mram_dual_port_max_pool_1_inst (.mram_addr_a({maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_mram_addr_a_netbus}), 
            .mram_din_a({maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_mram_din_a_netbus}), 
            .mram_dout({mram_dual_port_max_pool_1_inst_mram_dout_netbus}), 
            .mram_we_a({maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_mram_we_a_netbus}), 
            .read_addr({depthandpointwise_conv2d_112_56_2x_144ch_inst_pool_read_addr_netbus}), 
            .clk(clk), .mram_en_a(maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_mram_en_a_net), 
            .mram_en_b(maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_mram_en_b_net), 
            .resetn(resetn));
    mram_model_max_pool_2 mram_dual_port_max_pool_2_inst (.mram_addr_a({maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_mram_addr_a_netbus}), 
            .mram_din_a({maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_mram_din_a_netbus}), 
            .mram_dout({mram_dual_port_max_pool_2_inst_mram_dout_netbus}), 
            .mram_we_a({maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_mram_we_a_netbus}), 
            .read_addr({depthandpointwise_conv2d_28_7_3x_1280ch_inst_pool_read_addr_netbus}), 
            .clk(clk), .mram_en_a(maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_mram_en_a_net), 
            .mram_en_b(maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_mram_en_b_net), 
            .resetn(resetn));
    mram_model_maxpool mram_model_maxpool_inst (.mram_addr_a({maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_mram_addr_a_netbus}), 
            .mram_din_a({maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_mram_din_a_netbus}), 
            .mram_dout_b({mram_model_maxpool_inst_mram_dout_b_netbus}), .mram_we_a({maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_mram_we_a_netbus}), 
            .read_addr({dense_layer_1x_1280_256_128_bn_relu6_top_inst_mp_read_addr_netbus}), 
            .clk(clk), .mram_en_a(maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_mram_en_a_net), 
            .mram_en_b(maxpool2d_7x7_stride7_16_batches_7_1_1280ch_top_inst_mram_en_b_net), 
            .resetn(resetn));
    pipeline_cpu pipeline_cpu_inst (.ex_mem_rd({pipeline_cpu_inst_ex_mem_rd_netbus}), 
            .ex_mem_rs2({pipeline_cpu_inst_ex_mem_rs2_netbus}), .ex_mem_val({pipeline_cpu_inst_ex_mem_val_netbus}), 
            .ex_rd({execute_stage_inst_ex_rd_netbus}), .ex_rs2({execute_stage_inst_ex_rs2_netbus}), 
            .ex_val({execute_stage_inst_ex_val_netbus}), .fetch_instr({fetch_unit_inst_fetch_instr_netbus}), 
            .id_ex_imm({pipeline_cpu_inst_id_ex_imm_netbus}), .id_ex_instr({pipeline_cpu_inst_id_ex_instr_netbus}), 
            .id_ex_rd({pipeline_cpu_inst_id_ex_rd_netbus}), .id_ex_rs1({pipeline_cpu_inst_id_ex_rs1_netbus}), 
            .id_ex_rs1_idx({pipeline_cpu_inst_id_ex_rs1_idx_netbus}), .id_ex_rs2({pipeline_cpu_inst_id_ex_rs2_netbus}), 
            .id_ex_rs2_idx({pipeline_cpu_inst_id_ex_rs2_idx_netbus}), .id_imm({decode_stage_inst_imm_out_netbus}), 
            .id_instr({decode_stage_inst_instr_out_netbus}), .id_rd({decode_stage_inst_rd_out_netbus}), 
            .id_rs1({decode_stage_inst_rs1_out_netbus}), .id_rs1_data({decode_stage_inst_rs1_data_out_netbus}), 
            .id_rs2({decode_stage_inst_rs2_out_netbus}), .id_rs2_data({decode_stage_inst_rs2_data_out_netbus}), 
            .if_id_instr({pipeline_cpu_inst_if_id_instr_netbus}), .mem_rd({memory_stage_inst_mem_wb_rd_netbus}), 
            .mem_val({memory_stage_inst_mem_wb_val_netbus}), .mem_wb_rd({pipeline_cpu_inst_mem_wb_rd_netbus}), 
            .mem_wb_val({pipeline_cpu_inst_mem_wb_val_netbus}), .result({pipeline_cpu_inst_result_netbus}), 
            .clk(clk), .ex_is_cnn(execute_stage_inst_ex_is_cnn_net), .ex_mem_is_cnn(pipeline_cpu_inst_ex_mem_is_cnn_net), 
            .ex_mem_valid(pipeline_cpu_inst_ex_mem_valid_net), .ex_valid(execute_stage_inst_ex_valid_net), 
            .fetch_valid(fetch_unit_inst_fetch_valid_net), .id_ex_is_accel(pipeline_cpu_inst_id_ex_is_accel_net), 
            .id_ex_rd_valid(pipeline_cpu_inst_id_ex_rd_valid_net), .id_is_accel(decode_stage_inst_is_accel_out_net), 
            .id_rd_valid(decode_stage_inst_rd_valid_out_net), .if_id_valid(pipeline_cpu_inst_if_id_valid_net), 
            .mem_is_cnn(memory_stage_inst_mem_wb_is_cnn_net), .mem_valid(memory_stage_inst_mem_wb_valid_net), 
            .mem_wb_is_cnn(pipeline_cpu_inst_mem_wb_is_cnn_net), .mem_wb_valid(pipeline_cpu_inst_mem_wb_valid_net), 
            .reset(resetn));
    register_file_1 register_file_1_inst (.rs1({decode_stage_inst_rf_rs1_addr_netbus}), 
            .rs2({decode_stage_inst_rf_rs2_addr_netbus}), .rs1_data({register_file_1_inst_rs1_data_netbus}), 
            .rs2_data({register_file_1_inst_rs2_data_netbus}), .clk(clk), 
            .rst(resetn), .rd_write_enable(writeback_stage_inst_wb_valid_net));
    register_file_2 register_file_2_inst (.rs1({decode_stage_inst_rf_rs1_addr_netbus}), 
            .rs1_data({register_file_2_inst_rs1_data_netbus}), .rs2({decode_stage_inst_rf_rs2_addr_netbus}), 
            .rs2_data({register_file_2_inst_rs2_data_netbus}), .clk(clk), 
            .rd_write_enable(writeback_stage_inst_wb_valid_net), .rst(resetn));
    register_file_3 register_file_3_inst (.rs1({decode_stage_inst_rf_rs1_addr_netbus}), 
            .rs1_data({register_file_3_inst_rs1_data_netbus}), .rs2({decode_stage_inst_rf_rs2_addr_netbus}), 
            .rs2_data({register_file_3_inst_rs2_data_netbus}), .clk(clk), 
            .rd_write_enable(writeback_stage_inst_wb_valid_net), .rst(resetn));
    register_file_4 register_file_4_inst (.rs1({decode_stage_inst_rf_rs1_addr_netbus}), 
            .rs1_data({register_file_4_inst_rs1_data_netbus}), .rs2({decode_stage_inst_rf_rs2_addr_netbus}), 
            .rs2_data({register_file_4_inst_rs2_data_netbus}), .clk(clk), 
            .rd_write_enable(writeback_stage_inst_wb_valid_net), .rst(resetn));
    register_file_5 register_file_5_inst (.rs1({decode_stage_inst_rf_rs1_addr_netbus}), 
            .rs1_data({register_file_5_inst_rs1_data_netbus}), .rs2({decode_stage_inst_rf_rs2_addr_netbus}), 
            .rs2_data({register_file_5_inst_rs2_data_netbus}), .clk(clk), 
            .rd_write_enable(writeback_stage_inst_wb_valid_net), .rst(resetn));
    register_file_6 register_file_6_inst (.rs1({decode_stage_inst_rf_rs1_addr_netbus}), 
            .rs1_data({register_file_6_inst_rs1_data_netbus}), .rs2({decode_stage_inst_rf_rs2_addr_netbus}), 
            .rs2_data({register_file_6_inst_rs2_data_netbus}), .clk(clk), 
            .rd_write_enable(writeback_stage_inst_wb_valid_net), .rst(resetn));
    register_file_7 register_file_7_inst (.rs1({decode_stage_inst_rf_rs1_addr_netbus}), 
            .rs1_data({register_file_7_inst_rs1_data_netbus}), .rs2({decode_stage_inst_rf_rs2_addr_netbus}), 
            .rs2_data({register_file_7_inst_rs2_data_netbus}), .clk(clk), 
            .rd_write_enable(writeback_stage_inst_wb_valid_net), .rst(resetn));
    register_file_8 register_file_8_inst (.rs1({decode_stage_inst_rf_rs1_addr_netbus}), 
            .rs1_data({register_file_8_inst_rs1_data_netbus}), .rs2({decode_stage_inst_rf_rs2_addr_netbus}), 
            .rs2_data({register_file_8_inst_rs2_data_netbus}), .clk(clk), 
            .rd_write_enable(writeback_stage_inst_wb_valid_net), .rst(resetn));
    register_file_9 register_file_9_inst (.rs1({decode_stage_inst_rf_rs1_addr_netbus}), 
            .rs1_data({register_file_9_inst_rs1_data_netbus}), .rs2({decode_stage_inst_rf_rs2_addr_netbus}), 
            .rs2_data({register_file_9_inst_rs2_data_netbus}), .clk(clk), 
            .rd_write_enable(writeback_stage_inst_wb_valid_net), .rst(resetn));
    register_file register_file_inst (.rs1({decode_stage_inst_rf_rs1_addr_netbus}), 
            .rs1_data({register_file_inst_rs1_data_netbus}), .rs2({decode_stage_inst_rf_rs2_addr_netbus}), 
            .rs2_data({register_file_inst_rs2_data_netbus}), .clk(clk), 
            .rd_write_enable(writeback_stage_inst_wb_valid_net), .rst(resetn));
    scale_rom_1 scale_rom_1_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_scale_addr_netbus}), 
            .data({scale_rom_1_inst_data_netbus}));
    scale_rom_dense_layer_1x_1280_256_128_bn_relu6 scale_rom_dense_layer_1x_1280_256_128_bn_relu6_inst (.addr({dense_layer_1x_1280_256_128_bn_relu6_top_inst_scale_addr_netbus}), 
            .data({scale_rom_dense_layer_1x_1280_256_128_bn_relu6_inst_data_netbus}));
    scale_rom_depthwise_pointwise_2 scale_rom_depthwise_pointwise_2_inst (.addr({depthandpointwise_conv2d_112_56_2x_144ch_inst_filter_idx_netbus}), 
            .data({scale_rom_depthwise_pointwise_2_inst_data_netbus}));
    scale_rom_depthwise_pointwise_3 scale_rom_depthwise_pointwise_3_inst (.addr({depthandpointwise_conv2d_28_7_3x_1280ch_inst_filter_idx_netbus}), 
            .data({scale_rom_depthwise_pointwise_3_inst_data_netbus}));
    depthwise_mram second_order_conv_mram_wrapper_inst (.mram_addr_a({depthandpointwise_conv2d_112_56_2x_144ch_inst_mram_addr_a_netbus}), 
            .mram_din_a({depthandpointwise_conv2d_112_56_2x_144ch_inst_mram_din_a_netbus}), 
            .mram_dout_b({second_order_conv_mram_wrapper_inst_mram_dout_b_netbus}), 
            .mram_we_a({depthandpointwise_conv2d_112_56_2x_144ch_inst_mram_we_a_netbus}), 
            .read_addr({maxpool2d_2x2_stride2_16_batches_56_56_144ch_mram_inst_conv2d_read_addr_netbus}), 
            .clk(clk), .mram_en_a(depthandpointwise_conv2d_112_56_2x_144ch_inst_mram_en_a_net), 
            .mram_en_b(depthandpointwise_conv2d_112_56_2x_144ch_inst_mram_en_b_net), 
            .resetn(resetn));
    shift_rom_1 shift_rom_1_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_shift_addr_netbus}), 
            .data({shift_rom_1_inst_data_netbus}));
    shift_rom_dense_layer_1x_1280_256_128_bn_relu6 shift_rom_dense_layer_1x_1280_256_128_bn_relu6_inst (.addr({dense_layer_1x_1280_256_128_bn_relu6_top_inst_shift_addr_netbus}), 
            .data({shift_rom_dense_layer_1x_1280_256_128_bn_relu6_inst_data_netbus}));
    shift_rom_depthwise_pointwise_2 shift_rom_depthwise_pointwise_2_inst (.addr({depthandpointwise_conv2d_112_56_2x_144ch_inst_filter_idx_netbus}), 
            .data({shift_rom_depthwise_pointwise_2_inst_data_netbus}));
    shift_rom_depthwise_pointwise_3 shift_rom_depthwise_pointwise_3_inst (.addr({depthandpointwise_conv2d_28_7_3x_1280ch_inst_filter_idx_netbus}), 
            .data({shift_rom_depthwise_pointwise_3_inst_data_netbus}));
    System_on_Chip soc_axi_full_inst (.instruction({instruction}), .m_axi_araddr({soc_axi_full_inst_m_axi_araddr_netbus}), 
            .m_axi_arburst({soc_axi_full_inst_m_axi_arburst_netbus}), .m_axi_arcache({soc_axi_full_inst_m_axi_arcache_netbus}), 
            .m_axi_arid({soc_axi_full_inst_m_axi_arid_netbus}), .m_axi_arlen({soc_axi_full_inst_m_axi_arlen_netbus}), 
            .m_axi_arprot({soc_axi_full_inst_m_axi_arprot_netbus}), .m_axi_arqos({soc_axi_full_inst_m_axi_arqos_netbus}), 
            .m_axi_arsize({soc_axi_full_inst_m_axi_arsize_netbus}), .m_axi_awaddr({soc_axi_full_inst_m_axi_awaddr_netbus}), 
            .m_axi_awburst({soc_axi_full_inst_m_axi_awburst_netbus}), .m_axi_awcache({soc_axi_full_inst_m_axi_awcache_netbus}), 
            .m_axi_awid({soc_axi_full_inst_m_axi_awid_netbus}), .m_axi_awlen({soc_axi_full_inst_m_axi_awlen_netbus}), 
            .m_axi_awprot({soc_axi_full_inst_m_axi_awprot_netbus}), .m_axi_awqos({soc_axi_full_inst_m_axi_awqos_netbus}), 
            .m_axi_awsize({soc_axi_full_inst_m_axi_awsize_netbus}), .m_axi_bid({bootloader_rom_inst_m_axi_bid_netbus}), 
            .m_axi_bresp({bootloader_rom_inst_m_axi_bresp_netbus}), .m_axi_rdata({AXI_Interface_inst_rdata_netbus}), 
            .m_axi_rid({bootloader_rom_inst_m_axi_rid_netbus}), .m_axi_rresp({bootloader_rom_inst_m_axi_rresp_netbus}), 
            .m_axi_wdata({soc_axi_full_inst_m_axi_wdata_netbus}), .m_axi_wstrb({soc_axi_full_inst_m_axi_wstrb_netbus}), 
            .prediction({prediction}), .s_axi_araddr({bootloader_rom_inst_s_axi_araddr_netbus}), 
            .s_axi_arburst({bootloader_rom_inst_s_axi_arburst_netbus}), .s_axi_arcache({bootloader_rom_inst_s_axi_arcache_netbus}), 
            .s_axi_arid({bootloader_rom_inst_s_axi_arid_netbus}), .s_axi_arlen({bootloader_rom_inst_s_axi_arlen_netbus}), 
            .s_axi_arprot({bootloader_rom_inst_s_axi_arprot_netbus}), .s_axi_arqos({bootloader_rom_inst_s_axi_arqos_netbus}), 
            .s_axi_arsize({bootloader_rom_inst_s_axi_arsize_netbus}), .s_axi_awaddr({bootloader_rom_inst_s_axi_awaddr_netbus}), 
            .s_axi_awburst({bootloader_rom_inst_s_axi_awburst_netbus}), .s_axi_awcache({bootloader_rom_inst_s_axi_awcache_netbus}), 
            .s_axi_awid({bootloader_rom_inst_s_axi_awid_netbus}), .s_axi_awlen({bootloader_rom_inst_s_axi_awlen_netbus}), 
            .s_axi_awprot({bootloader_rom_inst_s_axi_awprot_netbus}), .s_axi_awqos({bootloader_rom_inst_s_axi_awqos_netbus}), 
            .s_axi_awsize({bootloader_rom_inst_s_axi_awsize_netbus}), .s_axi_bid({soc_axi_full_inst_s_axi_bid_netbus}), 
            .s_axi_bresp({soc_axi_full_inst_s_axi_bresp_netbus}), .s_axi_rdata({soc_axi_full_inst_s_axi_rdata_netbus}), 
            .s_axi_rid({soc_axi_full_inst_s_axi_rid_netbus}), .s_axi_rresp({soc_axi_full_inst_s_axi_rresp_netbus}), 
            .s_axi_wdata({bootloader_rom_inst_s_axi_wdata_netbus}), .s_axi_wstrb({bootloader_rom_inst_s_axi_wstrb_netbus}), 
            .bootloader_start(soc_axi_full_inst_bootloader_start_net), .clk(clk), 
            .done(done), .m_axi_arlock(soc_axi_full_inst_m_axi_arlock_net), 
            .m_axi_arready(bootloader_rom_inst_m_axi_arready_net), .m_axi_arvalid(soc_axi_full_inst_m_axi_arvalid_net), 
            .m_axi_awlock(soc_axi_full_inst_m_axi_awlock_net), .m_axi_awready(bootloader_rom_inst_m_axi_awready_net), 
            .m_axi_awvalid(soc_axi_full_inst_m_axi_awvalid_net), .m_axi_bready(soc_axi_full_inst_m_axi_bready_net), 
            .m_axi_bvalid(bootloader_rom_inst_m_axi_bvalid_net), .m_axi_rlast(bootloader_rom_inst_m_axi_rlast_net), 
            .m_axi_rready(soc_axi_full_inst_m_axi_rready_net), .m_axi_rvalid(bootloader_rom_inst_m_axi_rvalid_net), 
            .m_axi_wlast(soc_axi_full_inst_m_axi_wlast_net), .m_axi_wready(bootloader_rom_inst_m_axi_wready_net), 
            .m_axi_wvalid(soc_axi_full_inst_m_axi_wvalid_net), .reset(resetn), 
            .s_axi_arlock(bootloader_rom_inst_s_axi_arlock_net), .s_axi_arready(soc_axi_full_inst_s_axi_arready_net), 
            .s_axi_arvalid(bootloader_rom_inst_s_axi_arvalid_net), .s_axi_awlock(bootloader_rom_inst_s_axi_awlock_net), 
            .s_axi_awready(soc_axi_full_inst_s_axi_awready_net), .s_axi_awvalid(bootloader_rom_inst_s_axi_awvalid_net), 
            .s_axi_bready(bootloader_rom_inst_s_axi_bready_net), .s_axi_bvalid(soc_axi_full_inst_s_axi_bvalid_net), 
            .s_axi_rlast(soc_axi_full_inst_s_axi_rlast_net), .s_axi_rready(bootloader_rom_inst_s_axi_rready_net), 
            .s_axi_rvalid(soc_axi_full_inst_s_axi_rvalid_net), .s_axi_wlast(bootloader_rom_inst_s_axi_wlast_net), 
            .s_axi_wready(soc_axi_full_inst_s_axi_wready_net), .s_axi_wvalid(bootloader_rom_inst_s_axi_wvalid_net));
    std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst (.MRAM_PORTA_addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTA_addr_netbus}), 
            .MRAM_PORTA_rdata({mram_dual_port_inst_MRAM_PORTA_rdata_netbus}), 
            .MRAM_PORTA_wdata({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTA_wdata_netbus}), 
            .MRAM_PORTA_we({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTA_we_netbus}), 
            .MRAM_PORTB_addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTB_addr_netbus}), 
            .MRAM_PORTB_rdata({mram_dual_port_inst_MRAM_PORTB_rdata_netbus}), 
            .bias_addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_bias_addr_netbus}), 
            .bias_data({biases_rom_1_inst_data_netbus}), .img_addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_img_addr_netbus}), 
            .img_rom_data0({image_rom_input_32x32_1_inst_data_netbus}), .img_rom_data1({image_rom_input_32x32_2_inst_data_netbus}), 
            .img_rom_data10({image_rom_input_32x32_11_inst_data_netbus}), 
            .img_rom_data11({image_rom_input_32x32_12_inst_data_netbus}), 
            .img_rom_data12({image_rom_input_32x32_13_inst_data_netbus}), 
            .img_rom_data13({image_rom_input_32x32_14_inst_data_netbus}), 
            .img_rom_data14({image_rom_input_32x32_15_inst_data_netbus}), 
            .img_rom_data15({image_rom_input_32x32_16_inst_data_netbus}), 
            .img_rom_data16({image_rom_input_32x32_17_inst_data_netbus}), 
            .img_rom_data17({image_rom_input_32x32_18_inst_data_netbus}), 
            .img_rom_data18({image_rom_input_32x32_19_inst_data_netbus}), 
            .img_rom_data19({image_rom_input_32x32_20_inst_data_netbus}), 
            .img_rom_data2({image_rom_input_32x32_3_inst_data_netbus}), .img_rom_data3({image_rom_input_32x32_4_inst_data_netbus}), 
            .img_rom_data4({image_rom_input_32x32_5_inst_data_netbus}), .img_rom_data5({image_rom_input_32x32_6_inst_data_netbus}), 
            .img_rom_data6({image_rom_input_32x32_7_inst_data_netbus}), .img_rom_data7({image_rom_input_32x32_8_inst_data_netbus}), 
            .img_rom_data8({image_rom_input_32x32_9_inst_data_netbus}), .img_rom_data9({image_rom_input_32x32_10_inst_data_netbus}), 
            .input_image_index({execute_stage_inst_cnn_img_index_netbus}), 
            .read_addr({maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_conv2d_read_addr_netbus}), 
            .read_data({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_read_data_netbus}), 
            .scale_addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_scale_addr_netbus}), 
            .scale_data({scale_rom_1_inst_data_netbus}), .shift_addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_shift_addr_netbus}), 
            .shift_data({shift_rom_1_inst_data_netbus}), .weight_addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_weight_addr_netbus}), 
            .weight_data({weights_rom_1_inst_data_netbus}), .MRAM_PORTA_en(std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTA_en_net), 
            .MRAM_PORTB_en(std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_MRAM_PORTB_en_net), 
            .MRAM_PORTB_rdata_valid(mram_dual_port_inst_MRAM_PORTB_rdata_valid_net), 
            .clk(clk), .done(std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_done_net), 
            .resetn(resetn), .start(maxpool2d_2x2_stride2_16_batches_112_112_32ch_inst_conv2d_start_net));
    weights_rom_1 weights_rom_1_inst (.addr({std_conv2d_224_224_3_32batches_batchnorm_relu6_1x_32ch_27pes_inst_weight_addr_netbus}), 
            .data({weights_rom_1_inst_data_netbus}));
    weights_rom_dense_layer_2x_128_to_9 weights_rom_dense_layer_2x_128_to_9_inst (.addr({dense_layer_2x_128_to_9_inst_weight_addr_netbus}), 
            .data({weights_rom_dense_layer_2x_128_to_9_inst_data_netbus}));
    weights_rom_depthwise_pointwise_2 weights_rom_depthwise_pointwise_2_inst (.addr({depthandpointwise_conv2d_112_56_2x_144ch_inst_weight_idx_netbus}), 
            .data({weights_rom_depthwise_pointwise_2_inst_data_netbus}));
    weights_rom_depthwise_pointwise_3 weights_rom_depthwise_pointwise_3_inst (.addr({depthandpointwise_conv2d_28_7_3x_1280ch_inst_weight_idx_netbus}), 
            .data({weights_rom_depthwise_pointwise_3_inst_data_netbus}));
    writeback_stage writeback_stage_inst (.mem_rd({pipeline_cpu_inst_mem_wb_rd_netbus}), 
            .mem_val({pipeline_cpu_inst_mem_wb_val_netbus}), .clk(clk), 
            .mem_is_cnn(pipeline_cpu_inst_mem_wb_is_cnn_net), .mem_valid(pipeline_cpu_inst_mem_wb_valid_net), 
            .reset(resetn), .wb_valid(writeback_stage_inst_wb_valid_net));
endmodule
